### ISSUE TITLE
Sort an Array

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#11]
Given an array of integers nums, sort the array in ascending order.

```markdown 
Input: [5,2,3,1]
Output: [1,2,3,5]
```

Note:
```markdown 
1 <= A.length <= 10000
-50000 <= A[i] <= 50000
```

Code:
```markdown 
/**
 * @param {number[]} nums
 * @return {number[]}
 */
var sortArray = function(nums) {
    
};
```

See Problem [here](https://leetcode.com/problems/sort-an-array/)

**Comment by zjael** [comment]
Gonna give a try. :)

**Comment by gane5hvarma** [comment]
i can take this.

**Comment by PawanKolhe** [comment]
#152 I made it, since its been 7 days since last assigned.
