### ISSUE TITLE
Regular Expression Matching

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#130]
See LeetCode Problem here: [Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching/)

Create your file in the folder `Backtracking` - don't forget to delete `Regular Expression Matching from the AlgorithmsToDo`-file

Given an input string (s) and a pattern (p), implement regular expression matching with support for '.' and '*'.

```
'.' Matches any single character.
'*' Matches zero or more of the preceding element.
```
The matching should cover the entire input string (not partial).

**Note:**
- s could be empty and contains only lowercase letters a-z.
- p could be empty and contains only lowercase letters a-z, and characters like . or *.

**Code:**
```
/**
 * @param {string} s
 * @param {string} p
 * @return {boolean}
 */
var isMatch = function(s, p) {
    
};
```

**Comment by ovalnine** [comment]
I would like to pick up this issue!
