### ISSUE TITLE
Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#131]
See LeetCode Problem here: [Letter Combinations](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)

Create your file in the folder `Backtracking` - don't forget to delete `Letter Combinations of a Phone Number` from the AlgorithmsToDo`-file

Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent.

A mapping of digit to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.

**Example:**
```
Input: "23"
Output: ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"].
```
**Note:**
Although the above answer is in lexicographical order, your answer could be in any order you want.

**Code:**
```
/**
 * @param {string} digits
 * @return {string[]}
 */
var letterCombinations = function(digits) {
    
};
```

**Comment by ghost** [comment]
This looks like fun. Can I take a stab at it? Also, would you want to limit the input length?

**Comment by vJechsmayr** [comment]
@jacob-shu Yes good idea! Limit the input length to 12 numbers.

Have fun :)

**Comment by rajneeshkumar146** [comment]
very easy to solve can I get it to
