### ISSUE TITLE
Generate Parentheses

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#132]
See LeetCode Problem [here](https://leetcode.com/problems/generate-parentheses/)

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

For example, given n = 3, a solution set is:

```
[
  "((()))",
  "(()())",
  "(())()",
  "()(())",
  "()()()"
]
```

**Code**
/**
  @param {number} n
  @return {string[]}
 */
var generateParenthesis = function(n) {
    
};

**Comment by rajneeshkumar146** [comment]
I want to grab this.
