### ISSUE TITLE
Combination Sum

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#134]
Create File `combinationSum.js` into directory `Backtracking`

See LeetCodeProblem [here](https://leetcode.com/problems/combination-sum/)

Create your file in the folder `Backtracking` - don't forget to delete `Combination Sum` from the AlgorithmsToDo`-file

Given a set of candidate numbers (candidates) (without duplicates) and a target number (target), find all unique combinations in candidates where the candidate numbers sums to target.

The same repeated number may be chosen from candidates unlimited number of times.

**Note:**
- All numbers (including target) will be positive integers.
- The solution set must not contain duplicate combinations.

**Example 1:**

```
Input: candidates = [2,3,6,7], target = 7,
A solution set is:
[
  [7],
  [2,2,3]
]
```

**Comment by rajneeshkumar146** [comment]
I want to grab this.

**Comment by ongzx** [comment]
I would like to take this one if it is still open.

**Comment by ongzx** [comment]
#149
