### ISSUE TITLE
N-Queens

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#135]
Create file `nqueens.js` at folder `Backtracking` - don't forget to delete `Combination Sum` from the AlgorithmsToDo`-file

See LeetCode Problem [here](https://leetcode.com/problems/n-queens/)

The n-queens puzzle is the problem of placing n queens on an n×n chessboard such that no two queens attack each other.

Given an integer n, return all distinct solutions to the n-queens puzzle.

Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space respectively.

**Example:**
```
Input: 4
Output: [
 [".Q..",  // Solution 1
  "...Q",
  "Q...",
  "..Q."],

 ["..Q.",  // Solution 2
  "Q...",
  "...Q",
  ".Q.."]
]
```

**Comment by rajneeshkumar146** [comment]
I want to grab this.

**Comment by Apoorv-Gaurav-Agarwal** [comment]
If this is still available, I would like to work upon this :)

**Comment by Kuljeet-123** [comment]
@vJechsmayr  I would like to do this.
