### ISSUE TITLE
Restore IP-Addresses

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#136]
Create file `restore_ipAddresses.js` it folder `Backtracking` - don't forget to delete `Combination Sum` from the AlgorithmsToDo`-file

See LeetCode Problem [here](https://leetcode.com/problems/restore-ip-addresses/)

Given a string containing only digits, restore it by returning all possible valid IP address combinations.

**Example:**
```
Input: "25525511135"
Output: ["255.255.11.135", "255.255.111.35"]
```

**Comment by rajneeshkumar146** [comment]
I want to grab this.

**Comment by Apoorv-Gaurav-Agarwal** [comment]
I can help
