### ISSUE TITLE
Roman to (decimal) Number

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#14]
Algorithm to Convert a Roman Number to a decimal Number

```markdown 
Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
```

Example:
```markdown 
Input: "IV"
Output: 4
```

See Problem [here](https://leetcode.com/problems/roman-to-integer/)

**Comment by alexgaddy** [comment]
I will try to make it.

**Comment by vJechsmayr** [comment]
#24 commited - close issue

**Comment by vJechsmayr** [comment]
multiple solutions are okay - I will have a closer look on weekends over all PRs
