### ISSUE TITLE
Day of the Week

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#140]
See LeetCode Problem [here](https://leetcode.com/problems/day-of-the-week/)

**Insert file `1185_DayOfTheWeek.js` into folder `LeetCode Solutions`**

Given a date, return the corresponding day of the week for that date.

The input is given as three integers representing the day, month and year respectively.

Return the answer as one of the following values {"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"}.

 

**Example 1:**
```
Input: day = 31, month = 8, year = 2019
Output: "Saturday"
```

**Example 2:**
```
Input: day = 18, month = 7, year = 1999
Output: "Sunday"
```
**Example 3:**
```
Input: day = 15, month = 8, year = 1993
Output: "Sunday"
```
 
**Constraints:**
- The given dates are valid dates between the years 1971 and 2100.

**Comment by rajneeshkumar146** [comment]
I want to grab this can you please assign it to me.

**Comment by ElIkone** [comment]
I want to grab this one
