### ISSUE TITLE
Permutations Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#156]
See LeetCode Problem [here](https://leetcode.com/problems/permutations/)

Given a collection of distinct integers, return all possible permutations.

**Example:**
```
Input: [1,2,3]
Output:
[
  [1,2,3],
  [1,3,2],
  [2,1,3],
  [2,3,1],
  [3,1,2],
  [3,2,1]
]
```

**Code:**
```
/**
 * @param {number[]} nums
 * @return {number[][]}
 */
var permute = function(nums) {
    
};
```

**Comment by rainerkent** [comment]
Hello @vJechsmayr, I'd like to work on this.
