### ISSUE TITLE
Permutations 2 Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#157]
See LeetCode Problem [here](https://leetcode.com/problems/permutations-ii/)

Given a collection of numbers that might contain duplicates, return all possible unique permutations.

**Example:**
```
Input: [1,1,2]
Output:
[
  [1,1,2],
  [1,2,1],
  [2,1,1]
]
```

**Code**
```
/**
 * @param {number[]} nums
 * @return {number[][]}
 */
var permuteUnique = function(nums) {
    
};
```

**Comment by andregallacci** [comment]
I'm going to start working on it!

**Comment by saichandernagamalla** [comment]
@vJechsmayr I would like to contribute.

**Comment by saichandernagamalla** [comment]
@vJechsmayr Raised PR, can you please review the code.
