### ISSUE TITLE
Subsets

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#159]
See LeetCode Problem [here](https://leetcode.com/problems/subsets/)

Given a set of distinct integers, nums, return all possible subsets (the power set).

Note: The solution set must not contain duplicate subsets.

**Example:**
```
Input: nums = [1,2,3]
Output:
[
  [3],
  [1],
  [2],
  [1,2,3],
  [1,3],
  [2,3],
  [1,2],
  []
]
```

**Code**
```
/**
 * @param {number[]} nums
 * @return {number[][]}
 */
var subsets = function(nums) {
    
};
```

**Comment by rajneeshkumar146** [comment]
I'm doing it.

**Comment by jrga03** [comment]
is this still open?
