### ISSUE TITLE
Permutation Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#17]
Given a collection of distinct integers, return all possible permutations.

```
Input: [1,2,3]
Output:
[
  [1,2,3],
  [1,3,2],
  [2,1,3],
  [2,3,1],
  [3,1,2],
  [3,2,1]
]
```

See Problem [here](https://leetcode.com/problems/permutations/)

**Comment by gane5hvarma** [comment]
i can pick it up.

**Comment by aemiralfath** [comment]
Can I take this issue? I can pick it up too

**Comment by ongzx** [comment]
#126
