### ISSUE TITLE
Solutions for LeetCode in JavaScript

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#2]
You can contribute solutions for LeetCode algorithm with the programming language **JavaScript**

Look in the folders for the `Algorithms_ToDo`-file to see which Problems are **open to contribute**.

Good practice coding :)

**Comment by aprilxyc** [comment]
Hello, keen on developing my Javascript skills! Can I be assigned to this one and contribute Leetcode solutions?

**Comment by vJechsmayr** [comment]
Feel Free

**Comment by ongzx** [comment]
#150
