### ISSUE TITLE
Wildcard Matching Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#25]
See Problem [here](https://leetcode.com/problems/wildcard-matching/)

Create your file in the folder `Backtracking` - don't forget to delete `Wildcard Matching` from the AlgorithmsToDo`-file

Given an input string (s) and a pattern (p), implement wildcard pattern matching with support for '?' and '*'.

```
'?' Matches any single character.
'*' Matches any sequence of characters (including the empty sequence).
```

The matching should cover the entire input string (not partial).

Note:

s could be empty and contains only lowercase letters a-z.
p could be empty and contains only lowercase letters a-z, and characters like ? or *.

Example:
```
Input:
s = "aa"
p = "*"
Output: true
Explanation: '*' matches any sequence.
```

**Comment by isamrish** [comment]
@vJechsmayr -- I like to do this. please assign me.

**Comment by rajneeshkumar146** [comment]
Can you please assign to me
