### ISSUE TITLE
Setup/Organisation Structure

### ISSUE THREAD

**Issue by Quadriphobs1** [vJechsmayr/JavaScriptAlgorithms#26]
It would be a good idea to have few things in place for a good organisation and to support for a contribution

1. Contribution guide
2. License
3. Use of JavaScript/Node package.json to manage commands
4. Writing extensive for each algorithm to verify its validity
5. Folder organisation for each algorithm in its own scope

Suggetion for folder

```
package.json
insertionsort/
insertionsort/insertionsort.js
insertionsort/insertionsort.test.js
```

I can create a quick PR for the folder organisation if that will be welcomed

**Comment by vJechsmayr** [comment]
Good Idea! Feel Free to Setup A Folder Organisation
