### ISSUE TITLE
Fibonacci Search Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#34]
Given a sorted array arr[] of size n and an element x to be searched in it. Return index of x if it is present in array else return -1.
Examples:

```
Input:  arr[] = {2, 3, 4, 10, 40}, x = 10
Output:  3
Element x is present at index 3.

Input:  arr[] = {2, 3, 4, 10, 40}, x = 11
Output:  -1
Element x is not present.
```

Fibonacci Search is a comparison-based technique that uses Fibonacci numbers to search an element in a sorted array.

**Comment by shivambatsgit** [comment]
Can I take this up?

**Comment by BalgopalPatro** [comment]
Can I do the code for this ??

**Comment by shivambatsgit** [comment]
@vJechsmayr I have created the PR for the same!
Can you check?

**Comment by vJechsmayr** [comment]
@shivambats please reference your PR to this issue so i can find it - tkx
