### ISSUE TITLE
Decimal to Binary Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#35]

**Comment by itsGabriel** [comment]
Can you sign it to me?

**Comment by agnideepmukherjee** [comment]
i also want to contribute.how can i start?

**Comment by itsGabriel** [comment]
@vJechsmayr You already solved this issue, what happen?

**Comment by vJechsmayr** [comment]
@itsGabriel feel free to commit your solution - was working on this - but issue is still open

**Comment by vJechsmayr** [comment]
@agnideepzayn write your code and create a Pull Request - multiple solutions are okay for me - I have a closer look on weekends
