### ISSUE TITLE
Decimal To Octal Algorithm

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#41]

**Comment by qdtroemner** [comment]
https://github.com/vJechsmayr/JavaScriptAlgorithms/pull/45

Here is my addition.

**Comment by vJechsmayr** [comment]
multiple solutions are okay - I will have a closer look on weekends over all PRs

**Comment by eduqg** [comment]
Another solution with expression [here](https://github.com/vJechsmayr/JavaScriptAlgorithms/pull/91)
