### ISSUE TITLE
Two Sum

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/JavaScriptAlgorithms#68]
See Problem here: [Two Sum](https://leetcode.com/problems/two-sum/)

Add your Solution to the `Other Algorithm` Directory

**Comment by psalmfill** [comment]
@vJechsmayr let me work on this

**Comment by rubiin** [comment]
pr here https://github.com/vJechsmayr/JavaScriptAlgorithms/pull/71 @vJechsmayr

**Comment by Bl4sio** [comment]
my solution: #72

**Comment by mrcongliu** [comment]
My solution using cache: [#76 ](https://github.com/vJechsmayr/JavaScriptAlgorithms/pull/76)

**Comment by LuigiLegion** [comment]
Here's my solution using pointers: https://github.com/vJechsmayr/JavaScriptAlgorithms/pull/79

**Comment by PawanKolhe** [comment]
A simple solution: #84

**Comment by caleywoods** [comment]
@LuigiLegion That solution is optimal only if the array is sorted and that is not guaranteed (and not the case) in this problem. I tried to go for that approach at first as well.

**Comment by vJechsmayr** [comment]
Thanks for contributing :)
